### ISSUE TITLE
Enabling `BPPARAM` for BiocParallel::bplapply in clusterSeq

### ISSUE THREAD

**Issue by pmb59** [tjh48/clusterSeq#1]

**Comment by hpages** [comment]
Dear @pmb59,

It seems that you are suggesting a simple change to the **clusterSeq** package. However you start your post above by tagging people that have nothing to do with the development of the **clusterSeq** package (@mtmorgan, @vobencha, and myself), which is somewhat confusing. Please edit your post above to make your request very clear. 

Now it seems that at the same time you are suggesting a modification "in Bioconductor", which is very vague to say the least. What package exactly are you talking about? Can you please suggest the change again by opening an issue for that package?

Thanks,
H.
